### PR TITLE
Escape HTML in messages extracted from Validator NU output

### PR DESCRIPTION
**Pull request by dontcallmedom**
Fix XSS risk

@jean-gui I haven't tested it and am light years away of being in a position to test it, so your help in verifying this fix the bug and in deploying it if it does would be greatly appreciated

### CODE REVIEW

**Comment by savproga** [comment]
Hi! I was the one who reported the vulnerability. I'm sorry if my words are out of place. But I didn't manage to deploy the unicorn (http://80.211.182.47:8081/unicorn/), but it turned out only part of it because the markup-validator observer does not work. The thing is that it uses the scheme that is described in the file https://validator.w3.org/unicorn/contracts/markup-validator.wadl. But the validator in this scheme makes a 301 redirect to the new NU. Here is an excerpt from the unicorn log http://validator.w3.org/check?uri=uxel.ru&output=ucn - in theory, we should see xml (as in other validators), but instead of XML, we get 301 redirects. I may be wrong about wadl, but everything works for me except NU. I would be happy to check the proposed edit myself, on my stand, and substitute my XSS Payloads

**Comment by savproga** [comment]
@dontcallmedom @jean-gui I was the one who reported the vulnerability. I'm sorry if my words are inappropriate. But I was unable to deploy the unicorn and check the suggested edits. Everything worked perfectly, XSS on my Payloads are no longer observed. HTML is escaped. You can check it here: http://80.211.182.47:8081/unicorn/check?ucn_uri=uxel.ru&ucn_lang=ru&ucn_task=conformance#

**Comment by dontcallmedom** [comment]
@savproga many thanks for verifying the patch! I'll work with @jean-gui in getting it deployed then.

**Comment by chat3d** [comment]
thank you

**Pull request merged**
